### ISSUE TITLE
Not an editor command: BundleInstall 

### ISSUE THREAD

**Issue by levylll** [M-Kepler/KeplerVim#2]
请问这个错误要怎么处理呢。。。。。搞了好久了，一直没法完整的配好环境，请求指点一下，多谢了。

**Comment by M-Kepler** [comment]
是vundle没装吗?  或者提示错误里有" EOF" 的话请看我 安装-第四点-引用哪里, 把vimrc里几行代码注释掉,
 再试一次就可以了.  我改了一下 REAME.md 你看一下

**Comment by levylll** [comment]
现在的问题是YCM的问题了，这个我在装k-vim也是类似的
错误如下
```
YouCompleteMe unavailable: dlopen(/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so, 2): Symbol not found: __PyCodecInfo_GetIncrementalDecode
r
  Referenced from: /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so
  Expected in: flat namespace
 in /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so
```
我是要下载你的包，然后移进去么

**Comment by levylll** [comment]
edsono/vim-matchit
这个好像装不了。。。。

**Comment by levylll** [comment]
YCM的问题解决了，似乎是因为python版本的问题，我使用brew uninstall python 把python版本降下来就可以了。。。。。
但是出现了 pylint 相关的错误。。。。。
啊，真难！

**Comment by M-Kepler** [comment]
我没在mac下尝试过...我这个配置是在ubuntu下用的...尴尬了

**Comment by levylll** [comment]
尴尬。。。。不过神奇的是问题都解决了，现在的唯一问题是图标问题，就是下面那个位置，在insert后面的小图标，我这里显示的是小问号。请问有没有解决方法呢？

**Comment by M-Kepler** [comment]
那个你参考一下 airline的安装, 只要安装一个特殊的字体,就好了, [博客](http://blog.csdn.net/the_victory/article/details/50638810)
